"""Create roles

Revision ID: 73f856b2ba63
Revises: 988163224181
Create Date: 2022-12-04 22:15:29.329690
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '73f856b2ba63'
down_revision = '988163224181'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'roles',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('role', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
