"""Create profiles

Revision ID: 7f77b33c3a7f
Revises: 8a985c4e0d9c
Create Date: 2022-12-04 22:27:41.438214
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '7f77b33c3a7f'
down_revision = '8a985c4e0d9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'profiles',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    # ### end Alembic commands ###
