"""Create users

Revision ID: 8feaba29dc09
Revises: 7f77b33c3a7f
Create Date: 2022-12-04 22:36:03.336631
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '8feaba29dc09'
down_revision = '7f77b33c3a7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('password', sa.String(), nullable=True),
        sa.Column('role_id', sa.String(), nullable=True),
        sa.Column('profile_id', sa.String(), nullable=True),
        sa.Column('contact_id', sa.String(), nullable=True),
        sa.Column('address_id', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['address_id'],
            ['addresses.id'],
        ),
        sa.ForeignKeyConstraint(
            ['contact_id'],
            ['contacts.id'],
        ),
        sa.ForeignKeyConstraint(
            ['profile_id'],
            ['profiles.id'],
        ),
        sa.ForeignKeyConstraint(
            ['role_id'],
            ['roles.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
