"""Create offers

Revision ID: 988163224181
Revises: a8934f542f31
Create Date: 2022-12-04 22:11:23.993280
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '988163224181'
down_revision = 'a8934f542f31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'offers',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('slug', sa.String(), nullable=True),
        sa.Column('category_id', sa.String(), nullable=True),
        sa.Column('product_id', sa.String(), nullable=True),
        sa.Column('discount', sa.Float(), nullable=True),
        sa.Column('created_at', sa.Date(), nullable=True),
        sa.Column('valid_until', sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ['category_id'],
            ['categories.id'],
        ),
        sa.ForeignKeyConstraint(
            ['product_id'],
            ['products.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers')
    # ### end Alembic commands ###
