"""Create products

Revision ID: a8934f542f31
Revises: f5ac06c5053f
Create Date: 2022-12-04 17:22:33.359870
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'a8934f542f31'
down_revision = 'f5ac06c5053f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'products',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('slug', sa.String(), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('resume', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
